[book]
authors = ["ratankaliani"]
language = "en"
multilingual = false
title = "OP Succinct book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
git-repository-url = "https://github.com/succinctlabs/op-succinct"
